version: '3.4'
 # Sección donde defines tus contenedores
services:
    cleanarchitecturedb:                                    # Nombre del contaider 1 : bd postgree
        image: postgres:16.0                                # Nombre de la Imagen que usara para crear el container (esta la descarga de Docker Hub)

    cleanarchitectureapi:                                   # Nombre del contaider 2 :  Nuestra aplicacion .NET
        image: ${DOCKER_REGISTRY-}cleanarchitectureapi      # nombre imagen en local de la app
        build:                                              # Construir la imagen desde un Dockerfile.
            context: .
            dockerfile: src/CleanArchitecture/CleanArchitecture.Api/Dockerfile      # ruta del DockerFile para que recoja el nombre de la imagen.
        

    
        
        
  